# Generated by Django 4.2.7 on 2023-11-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_userwallet_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userwallet",
            name="balance",
        ),
    ]
