# Generated by Django 4.2.7 on 2023-11-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_userwallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwallet",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
