# Generated by Django 4.2.7 on 2023-12-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user_bank_account",
        ),
    ]
